import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import NavbarComp from "./_Components/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark text-foreground bg-background">
        <NextUIProvider>
          <NavbarComp />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
